# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  DemoResourceGroupName: 'GilesDemoRG'
  AzureSub: 'Azure On Line Services(2482da3d-7516-4b32-9057-d311caa99664)'

#pool:
#  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: 'BuildAndPublish'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*[Tt]ests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Pipeline.Workspace)'
        zipAfterPublish: True

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Pipeline.Workspace)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
         SimpleDotNetCoreApp.ARM/**
         SimpleDotNetCoreApp.Selenium/**
        TargetFolder: '$(Pipeline.Workspace)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'drop'

- stage: Dev
  jobs:
    - deployment: DeployWebsite
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        WebAppName: 'GilesYAMLDemoDev'
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@1
                inputs:
                  buildType: 'current'
                  artifactName: 'drop'
                  targetPath: '$(System.ArtifactsDirectory)/drop'
              - task: AzureResourceGroupDeployment@2
                inputs:
                  azureSubscription: '$(AzureSub)'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(DemoResourceGroupName)'
                  location: 'North Europe'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.json'
                  csmParametersFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.parameters.json'
                  overrideParameters: '-hostingPlanName "webapphostingplan" -webSiteName $(WebAppName) -skuName "F1" -skuCapacity 1'
                  deploymentMode: 'Incremental'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$(AzureSub)'
                  appType: 'webApp'
                  appName: '$(WebAppName)'
                  package: '$(System.ArtifactsDirectory)/**/*.zip'
                  deploymentMethod: 'auto'
             

- stage: QA
  jobs:
    - deployment: DeployWebsite
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        WebAppName: 'GilesYAMLDemoQA'
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@1
                inputs:
                  buildType: 'current'
                  artifactName: 'drop'
                  targetPath: '$(System.ArtifactsDirectory)/drop'
              - task: AzureResourceGroupDeployment@2
                inputs:
                  azureSubscription: '$(AzureSub)'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(DemoResourceGroupName)'
                  location: 'North Europe'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.json'
                  csmParametersFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.parameters.json'
                  overrideParameters: '-hostingPlanName "webapphostingplan" -webSiteName $(WebAppName) -skuName "F1" -skuCapacity 1'
                  deploymentMode: 'Incremental'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$(AzureSub)'
                  appType: 'webApp'
                  appName: '$(WebAppName)'
                  package: '$(System.ArtifactsDirectory)/**/*.zip'
                  deploymentMethod: 'auto'

- stage: Prod
  jobs:
    - deployment: DeployWebsite
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        WebAppName: 'GilesYAMLDemoProd'
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@1
                inputs:
                  buildType: 'current'
                  artifactName: 'drop'
                  targetPath: '$(System.ArtifactsDirectory)/drop'
              - task: AzureResourceGroupDeployment@2
                inputs:
                  azureSubscription: '$(AzureSub)'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(DemoResourceGroupName)'
                  location: 'North Europe'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.json'
                  csmParametersFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.parameters.json'
                  overrideParameters: '-hostingPlanName "webapphostingplan" -webSiteName $(WebAppName) -skuName "F1" -skuCapacity 1'
                  deploymentMode: 'Incremental'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$(AzureSub)'
                  appType: 'webApp'
                  appName: '$(WebAppName)'
                  package: '$(System.ArtifactsDirectory)/**/*.zip'
                  deploymentMethod: 'auto'